### ISSUE TITLE
No possibility to get localized string based on the KEY in the code?

### ISSUE THREAD

**Issue by babazookz** [ibrahimpenekli/GameToolkit-Localization#12]
Is it possible this functionality is not implemented or I am just doing something wrong?

**Comment by ibrahimpenekli** [comment]
It is designed to use with an asset file rather than a key actually. Also you can do this manually;
1- Find all localized assets in the project
2- Iterate through them by comparing file name as a key

But it is slow process. You should reference the desired localized asset through the inspector like any other asset in Unity.
